User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - control'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
Error 2020-11-16 14:53:51: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/coolpp/tut/sel/playlist/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/coolpp/tut/sel/playlist/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:730:838)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:9:152841)
	at async p.doesFileNeedToBeFixed (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:39:468556)
	at async /home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:39:467683
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:39:467629)
	at async p.updateTestSettings (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:39:467256)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
Starting Jedi Python language engine.
Python interpreter path: /usr/bin/python3
> pyenv root
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tut/sel/playlist/main.py
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/tut/sel/playlist/main.py
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/tut/sel/playlist
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
Error 2020-11-16 14:53:53: stat() failed for "/home/coolpp/.local/lib/python3.6/site-packages" [NoPermissions (FileSystemError) (FileSystemError): Error: EACCES: permission denied, stat '/home/coolpp/.local/lib/python3.6/site-packages'
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:731:259)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async b.pathExists (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:9:154647)
	at async T.getPathFromPython (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:1:202924)
	at async Promise.all (index 3)
	at async T.buildAutoCompletePaths (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:1:203667)
	at async T.startLanguageServer (/home/coolpp/.vscode/extensions/ms-python.python-2020.11.358366026/out/client/extension.js:1:197866)] {
  code: 'Unknown',
  name: 'NoPermissions (FileSystemError) (FileSystemError)'
}
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/completion.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/completion.py

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
> pyenv root
> conda --version
> pyenv root
